---
title: "MBON Habitat Prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r setup}
library(sp)
library(rgdal)
library(raster)
library(tidyverse)
library(stringr)
library(knitr)

dir_data = switch(
  R.utils::System$getUsername(),
  bbest = '/Volumes/Best HD/mbon_data_big')

dir_hab = file.path(dir_data, 'halpernetal2015_habitats')
dir_tmp = file.path(dir_hab, 'tmp')
dir.create(dir_tmp, showWarnings=F)
dir.create(dir_hab, showWarnings=F)
```


## Download Habitats from Halpern et al (2015)

[Halpern et al. (2015) Cumulative human impacts: Supplementary data - KNB - doi:10.5063/F19Z92TW.](https://knb.ecoinformatics.org/#view/doi:10.5063/F19Z92TW)

```{r download & unzip, eval=F}
zip_url = 'https://knb.ecoinformatics.org/knb/d1/mn/v2/packages/application%2Fbagit-097/urn%3Auuid%3A5f309258-67c1-4e62-9f16-622a97508eb3'
zip     = file.path(dir_data, 'halpernetal2015_habitats.zip')

download.file(zip_url, zip)
unzip(zip, exdir=dir_hab, junkpaths=T)

for (p_zip in list.files(dir_hab, '.*\\.zip', full.names=T)){ # p_zip = list.files(dir_hab, '.*\\.zip', full.names=T)[1]
  unzip(p_zip, exdir=dir_hab)
}
```


## Raster Manipulation

- [8. Raster data manipulation](http://rspatial.org/spatial/rst/8-rastermanip.html)

```{r create hab_id}
tif_all  = file.path(dir_data, 'hab_id.tif')
csv_all  = file.path(dir_data, 'hab_id.csv')
csv_freq = file.path(dir_data, 'hab_id_freq.csv')

tifs = setdiff(
  list.files(dir_hab, '*.\\.tif$'),
  c('deep_waters_lzw.tif','habitat_num.tif','surface_waters_lzw.tif','ocean_mask.tif'))

d = data_frame(
  tif = tifs) %>%
  mutate(
    name   = str_replace(tifs, '_lzw.tif', ''),
    id     = sapply(c(1e0,1e1,1e2,1e3,1e4,1e5), function(x) x * c(1,2,4)) %>% as.vector(),
    tif_id = sprintf('%s_id.tif', name)); # View(d)

for (i in 1:nrow(d)){ # i=2
#for (i in 17:nrow(d)){ # i=2
  # vars
  lyr      = d$name[i]
  id       = d$id[i]
  lyr_id   = sprintf('%s_id', lyr)
  tif      = file.path(dir_hab, d$tif[i])
  tif_id   = file.path(dir_tmp, d$tif_id[i])

  # define layer as numeric id, otherwise 0
  if (!file.exists(tif_id)){
    t0 = Sys.time()
    cat(sprintf('%02d of %d: %s -> %s: 1 -> %d, otherwise 0 -- %s\n', i, nrow(d), lyr, lyr_id, id, Sys.time()))
    
    r = raster(tif)                      # read raster
    r = (1 - is.na(r)) * id              # assign unique habitat id, otherwise zero
    writeRaster(r, tif_id, overwrite=T)  # write tif
    
    dt = Sys.time() - t0
    cat(sprintf('  took %0.1f %s; estimated to complete %s\n', dt, attr(dt, 'units'), Sys.time() + dt*(nrow(d)-i)))
  }
}

r_m = stack(list.files(dir_tmp, '.*\\.tif', full.names=T)) %>% 
  sum() %>%      # sum across habitats
  mask(
    raster(file.path(dir_hab, 'ocean_mask.tif')), 
    maskvalue=0) # ocean is 79.3% of earth surface?

writeRaster(r_m, tif_all, overwrite=T)

r_m = raster(tif_all)

hab_in_value = function(val, hab, d){
# TODO: write function testing habitat for given pixel value, return True or False; 
#       to be used in dplyr::mutate() on freq() %>% as_tibble() for pixel value rows x hab columns
# - get digit in eth place (eg 2 for 1e2, ie 3 for 4321) using division modulus and remainder: 4321 %/% 1e2 %% 10 = 3
# - then use ifelse(value %in% ...
#   - 1 (eg beach):      c(1,3,5,7)
#   - 2 (eg coral_reef): c(2,3,6,7)
#   - 4 (eg d_h_bottom): c(4,5,6,7)
}
  
f = freq(r_m, useNA='ifany', progress='text')
f = f %>% 
  as_tibble() %>%
  mutate(
    count_m = count/1e6,
    pure = ifelse(value %in% d$id, T, F)) %>%
  arrange(desc(pure), desc(count)) %>%
  left_join(d, by=c('value'='id'))
  # d %>%
  #   mutate()
  #   spread(name)
  # View()
write_csv(f, csv_freq)
```

```{r raster stats}
grd      = 'H:/MBON/hab_prep_rc/reclass_sumd'
freq_csv = 'H:/MBON/hab_prep_rc/reclass_sumd_freq.csv'

r = raster(grd)
f = freq(r, useNA='ifany', progress='text')
f %>% 
  as_tibble() %>%
  mutate(
    count_m = count/1e6,
    pure = ifelse(value %in% d$hab_id, T, F)) %>%
  arrange(desc(pure), desc(count)) %>%
  left_join(d, by=c('value'='hab_id')) %>%
  View()

  write_csv(freq_csv)

#v = getValues(r)
#v_tbl = table(v)


```



```{r reclassify}
##figure out how to stick in for loop
t <- raster("H:/MBON/tmp/suspension_reef_num.tif")
m <- c(0,0,0, 18,18,400000)
rclmat <- matrix(m, ncol=3, byrow = TRUE)
rc <- reclassify(t, rclmat)
writeRaster(rc, filename = "H:/MBON/reclass/suspension_reef_num.tif")
```


```{r reclassify & crop}
tif_in    = 'H:/MBON/tmp/suspension_reef_num.tif'
tif_socal = 'H:/MBON/reclass/suspension_reef_num_socal.tif'
area      = 'socal'

##figure out how to stick in for loop
r = raster(tif_in)
m = matrix(
  c(0,0,0, 18,18,400000),
  ncol=3, byrow = TRUE)
r_r  = reclassify(r, m)

r_rc = crop(r_r, extent(study[[area]]))
writeRaster(r_rc, filename = tif_socal)

```

```{r, input raster setup download depth}
library(rgdal)  # geospatial data abstration library for R
library(raster)
library(marmap)  # geospatial data abstration library for R
#   see vignettes in https://cran.r-project.org/web/packages/marmap

# set working directory
setwd('P:/depth')



# old method
#r = raster::getData('SRTM', download=TRUE, path='.', lon=graysreef_xy[1], lat=graysreef_xy[2])

# get other data, including ecoregions for study area extent
mbnms_xy = c(-122.4404509, 36.5722023)
eco_rgn = readOGR('P:/study_area','cal_rgn_water')

# get bounding box of ecoregions
b = bbox(eco_rgn)

# get depth raster
depth <- getNOAA.bathy(
  lon1 = b[1], lon2 = b[3],
  lat1 = b[2], lat2 = b[4], resolution = 1)

# write to tif
raster::writeRaster(as.raster(depth), 'P:/depth/depth_calrgn_etopo1.tif')

# setup color palettes
blues <- c("lightsteelblue4", "lightsteelblue3",
           "lightsteelblue2", "lightsteelblue1")
greys <- c(grey(0.6), grey(0.93), grey(0.99))

# plot raster
plot(depth, image = TRUE, land = TRUE, lwd = 0.03,
     bpal = list(c(0, max(depth), greys),
                 c(min(depth), 0, blues)))
# plot coastline
plot(depth, n = 1, lwd = 0.4, add = TRUE)
```

