---
title: "water_mask"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sp)
library(rgdal)
library(raster)
library(tidyverse)
library(stringr)
library(knitr)
library(mapview)
library(marmap) # devtools::install_github('ericpante/marmap')

dir_data = switch(
  R.utils::System$getUsername(),
  bbest = '/Volumes/Best HD/mbon_data_big',
  sgad  = 'P:/habitats')

dir_hab = dir_data
dir_tmp = file.path(dir_hab, 'tmp')
dir.create(dir_tmp, showWarnings=F)
dir.create(dir_hab, showWarnings=F)


tif_all  = file.path(dir_data, 'hab_id.tif')
csv_all  = file.path(dir_data, 'hab_id.csv')
csv_sources = file.path('hab_sources.csv')
```

```{r crop to study areas}
# paths & vars
tif_m_g  = 'P:/habitats/ocean_mask.tif'
gdb      = 'H:/MBON/study_area.gdb'
regions  = c('southeast', 'southwest')

# read global water mask raster
r_m_g = raster(tif_m_g)
fact_9km = 9000 %/% xres(r_m_g)

for (rgn in regions){
  
  # set region specific paths
  tif_m     = sprintf('P:/habitats/%s_700buf-1km_mask.tif'   , rgn)
  tif_p     = sprintf('P:/habitats/%s_700buf-1km_patchid.tif', rgn)
  tif_m_9km = sprintf('P:/habitats/%s_700buf-9km_mask.tif'   , rgn)
  tif_p_9km = sprintf('P:/habitats/%s_700buf-9km_patchid.tif', rgn)

  # read in buffer in same projection as global water mask (Mollweide)
  buf = readOGR(gdb, sprintf('%s_700buf_mol', rgn))

  # generate Water mask raster & patch cover raster
  r_m = crop(r_m_g, buf) %>% # water = 1; land = 0
    trim() %>%
    mask(buf)
  r_m[r_m==0] = NA # convert land to NA for single mask value
  writeRaster(r_m, tif_m, dataType ='INT1U', overwrite=T)

  # generate patch IDs raster
  r_p = setValues(r_m, 1:ncell(r_m)) %>%
    mask(r_m)
  writeRaster(r_p, tif_p, dataType ='INT4S', overwrite=T)
  
  # reduce resolution, ie increase pixel size to 9 km
  r_m_9km = aggregate(r_m, fact_9km)
  writeRaster(r_m_9km, tif_m_9km, dataType ='INT1U', overwrite=T) 
  
  # generate patch IDs raster
  r_p_9km = setValues(r_m_9km, 1:ncell(r_m_9km)) %>%
    mask(r_m_9km)
  writeRaster(r_p_9km, tif_p_9km, dataType ='INT4S', overwrite=T)
  
}



```

